Serveur
Kumatetsu/my_slack pull request #6
Opened 2017-03-29 13:35 UTC by mesratn

Exemple serveur de la vidéo de cours

2017-03-29 15:29 UTC, Kumatetsu approved these changes
On a vu qu'il marche c'est OK

2017-03-29 15:33 UTC, Kumatetsu requested changes
hop hop hop, le main est dégueulasse, all in one c'est pas bon, faut m'éclater ça en sous fonctions ^^

2017-04-12 12:31 UTC, mesratn commented
Bah non ça c'est le main du prof avec tout mélangé. C'est juste un exemple, on va tout tout changé !

2017-04-12 13:05 UTC, Kumatetsu commented
Ba oui mais on peut le garder comme base non? ou alors tu laisses comme ça et quand on travaillera deçu on modifiera.

2017-04-17 10:44 UTC, closed without merging